name 'evenup-trusted_ca'
version '0.1.2'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
summary 'Manages host SSL certs.'
description 'Installs trusted root CAs into the default RH bundle'
project_page 'https://github.com/evenup/evenup-trusted_ca'
dependency 'ripienaar/concat', '>= 0.2.0'
